using UnityEngine;
using System.Collections;
using System;

public static class LOC_Strings
{

	public enum tLOC_Identifier
	{
		_UI_SPLASH_ASSOC_WITH = 0,
		_UI_FE_START = 1,
		_UI_FE_PLAYGAME = 2,
		_UI_FE_SETTINGS = 3,
		_UI_FE_EXITGAME = 4,
		_UI_FE_GRAPHICS = 5,
		_UI_FE_CONTROLS = 6,
		_UI_FE_GRAPHICSSETTINGS = 7,
		_UI_FE_PRESET = 8,
		_UI_FE_AA = 9,
		_UI_FE_AAType = 10,
		_UI_FE_VSYNC = 11,
		_UI_FE_FPS = 12,
		_UI_FE_SHADOWS = 13,
		_UI_FE_TEXTURES = 14,
		_UI_FE_BLOOM = 15,
		_UI_FE_VIGNETTE = 16,
		_UI_FE_LAPTOP = 17,
		_UI_FE_DESKTOP = 18,
		_UI_FE_RIG = 19,
		_UI_FE_LOW = 20,
		_UI_FE_MED = 21,
		_UI_FE_HIGH = 22,
		_UI_FE_OFF = 23,
		_UI_FE_ON = 24,
		_UI_FE_NEWGAME = 25,
		_UI_FE_CONTINUEGAME = 26,
		_UI_FE_BACK = 27,
		_UI_FE_NEXT = 28,
		_UI_FE_ORIENTATIONTITLE = 29,
		_UI_FE_TESTSELECTION = 30,
		_UI_FE_DOJOBACK = 31,
		_UI_PAUSE_SAVEQUIT = 32,
		_UI_PAUSE_QUIT = 33,
		_UI_FE_SELECT_GAME = 34,
		_UI_FE_MODE_ADVENTURE = 35,
		_UI_FE_MODE_OLD_SCHOOL = 36,
		_UI_FE_MODE_STRAP_ADVENTURE = 37,
		_UI_FE_MODE_STRAP_OLD_SCHOOL = 38,
		_UI_FE_CHAR_SELECT = 39,
		_UI_MAP_OLD_SCHOOL = 40,
		_UI_FE_CREDIT = 41,
		_UI_FE_SAVE_DELETE_DESC = 42,
		_UI_FE_SAVE_DELETE_YES = 43,
		_UI_FE_SAVE_DELETE_NO = 44,
		_UI_FE_SAVE_GAME_DESC = 45,
		_UI_FE_SAVE_GAME_TITLE = 46,
		_UI_FE_CONTINUE_DESC = 47,
		_UI_GAMEOVER_TITLE = 48,
		_UI_GAMEOVER_EXPLOR = 49,
		_UI_GAMEOVER_EXPLOR2 = 50,
		_UI_GAMEOVER_COLLECTED = 51,
		_UI_GAMEOVER_DUCKS = 52,
		_UI_GAMEOVER_FOUND = 53,
		_UI_GAMEOVER_CASSETTES = 54,
		_UI_GAMEOVER_JUMPED = 55,
		_UI_GAMEOVER_TIMES = 56,
		_UI_GAMEOVER_DIED = 57,
		_UI_GAMEOVER_HORRIBLE = 58,
		_UI_GAMEOVER_HIKED = 59,
		_UI_GAMEOVER_KILOMETERS = 60,
		_UI_GAMEOVER_TOTAL = 61,
		_UI_GAMEOVER_RETURN = 62,
		_UI_MINIGAME_OUTOFTIME = 63,
		_UI_MINIGAME_OUTOFLIVES = 64,
		_UI_FE_REFLECTIONS = 65,
		_CREDITS_BY = 66,
		_CREDITS_MUSIC = 67,
		_CREDITS_CHARACTER = 68,
		_CREDITS_TESTING = 69,
		_CREDITS_GIRLFRIEND = 70,
		_CREDITS_CAMEOS = 71,
		_CREDITS_ZZAP = 72,
		_CREDITS_MULTIFACE = 73,
		_CREDITS_RPI = 74,
		_CREDITS_LLAMASOFT = 75,
		_CREDITS_ATE_BIT = 76,
		_CREDITS_RITMAN = 77,
		_CREDITS_SHAHID = 78,
		_CREDITS_WILOVERTON = 79,
		_CREDITS_ZEE3 = 80,
		_CREDITS_JAS = 81,
		_CREDITS_RIKWILSON = 82,
		_CREDITS_NIPPER = 83,
		_CREDITS_HATTIP = 84,
		_CREDITS_ANDYOU = 85,
		_CREDITS_FORRSG = 86,
		_CREDITS_STINKYGOONER = 87,
		_CREDITS_OTHERGOONER = 88,
		_CREDITS_PRODMAN = 89,
		_CREDITS_DEVREL = 90,
		_CREDITS_PR = 91,
		_CREDITS_MARKETING = 92,
		_CREDITS_DIGITAL_MARKETING = 93,
		_UI_MINIGAME_GETREADY = 94,
		_UI_MINIGAME_GO = 95,
		_UI_FE_CANCEL = 96,
		_UI_FE_SETDEFAULTS = 97,
		_UI_FE_UP = 98,
		_UI_FE_DOWN = 99,
		_UI_FE_LEFT = 100,
		_UI_FE_RIGHT = 101,
		_UI_FE_JUMP = 102,
		_UI_FE_LAMP = 103,
		_UI_FE_MAP = 104,
		_UI_FE_BOOK = 105,
		_UI_FE_TILTLEFT = 106,
		_UI_FE_TILTRIGHT = 107,
		_UI_FE_REDEFINE = 108,
		_UI_FE_REDEFINE_EXP = 109,
		_UI_PAUSE_SETTINGS = 110,
		_UI_PAUSE_SETTINGS_EXP = 111,
		_UI_FE_LEADERBOARD = 112,
		_UI_FE_CREDITS = 113,
		_UI_LEADERBOARDS_TIMEOUT = 114,
		_UI_LEADERBOARDS_NO_ENTRIES = 115,
		_UI_LEADERBOARDS_NOT_FOUND = 116,
		_UI_LEADERBOARDS_STEAM_INIT = 117,
		_UI_LEADERBOARDS_WORLD = 118,
		_UI_LEADERBOARDS_YOU = 119,
		_UI_LEADERBOARDS_FRIENDS = 120,
		_CREDITS_FORJAW = 121,
		_CREDITS_PROGRAMMER = 122,
		_CREDITS_ART = 123,
		_CREDITS_QA = 124,
		_CREDITS_SUPPORT = 125,
		_CREDITS_THANKSTO = 126,
		_UI_AUTOSAVE = 127,
		_UI_SAVEPROBLEM = 128,
		_UI_RESOLUTION = 129,
		_UI_UPDATING = 130,
		_ = 131,
		_ = 132,
	};

	public static string[] LOC_EnglishStrings = {
		"In association with",
		"Start",
		"Play Game",
		"Settings",
		"Exit Game",
		"Graphics",
		"Controls",
		"Graphics Settings",
		"Preset:",
		"AA:",
		"AA Type:",
		"V-Sync:",
		"FPS:",
		"Shadows:",
		"Textures:",
		"Bloom:",
		"Vignette:",
		"Laptop",
		"Desktop",
		"Rig",
		"Low",
		"Med",
		"High",
		"Off",
		"On",
		"New Game",
		"Continue Game",
		"Back",
		"Next",
		"Please select controller orientation",
		"Test Selection",
		"Press to go back:",
		"Save & Quit",
		"Quit",
		"Please select a game type:",
		"Adventure",
		"Old School",
		"Infinite Lives. Map. Save Game. Explore in your own time!",
		"Finite Lives. No Map. No Save Game. Play against the clock like it's 1985!",
		"Please select a character:",
		"Map not available in Old School mode. ",
		"By Gareth Noyce",
		"Are you sure you want to delete this Save Game?",
		"Yes",
		"No",
		"Please select an empty Save Game Slot",
		"Save Game: ",
		"Please select a game to continue:",
		"Game Over",
		"While exploring",
		"rooms you:",
		"Collected",
		"Ducks",
		"Found",
		"Cassettes",
		"Jumped",
		"times",
		"Died in",
		"horrible ways",
		"And hiked",
		"kilometers",
		"Total time:",
		"Press START/ESC to return to the Main Menu",
		"Run out of time!",
		"No lives left!",
		"Reflections:",
		"Lumo, by:",
		"Music:",
		"Character Art:",
		"Testing:",
		"Girlfriend:",
		"Cameos:",
		"Zzap!64 logo © Oliver Frey. Used by kind permission of Oliver Frey and Roger Kean",
		"Multiface II used by kind permission of Romantic Robot, London (www.romantic-robot.com)",
		"Raspberry Pi (TM) used by kind permission of the Raspberry Pi Foundation (www.raspberrypi.org)",
		"Llamatron used by kind permission of Llamasoft Ltd (www.llamasoft.co.uk)",
		"Pimp My Spectrum used by kind permission of Ate Bit (www.atebit.org)",
		"Head Over Heels used by kind permission of Jon Ritman ",
		"Chimera used by kind permission of Shahid Ahmad ",
		"Alien 8 map used by kind permission of Wil Overton",
		"Amaurote screenshot used by kind permission of the Pickford Bros (www.zee-3.com)",
		"Rex Screenshot used by kind permission of Jas Austin",
		"'Hold My Hand Very Tightly' used by kind permission of David Wilson",
		"'Jack the Nipper' sprite used with kind permission of Ian Stewart. Greg Holmes, creator.",
		"Hat tips, Salutes & Hugs:",
		"And you…",
		"For Rising Star Games:",
		"Managing Director:",
		"Vice President (RSG Inc):",
		"Production Manager:",
		"Developer Relations:",
		"PR:",
		"Marketing:",
		"Digital Marketing:",
		"Get Ready…",
		"Go!",
		"Cancel",
		"Set Defaults",
		"Up:",
		"Down:",
		"Left:",
		"Right:",
		"Jump:",
		"Wand Light:",
		"Map:",
		"Book (Pause):",
		"Tilt Left:",
		"Tilt Right:",
		"Redefine Controls",
		"Click the button for the control you wish to change then press the desired input:",
		"Settings",
		"Some settings will only take effect in the next room",
		"Leaderboard",
		"Credits",
		"Leaderboard request timed out",
		"No entries found…",
		"Unable to find a Leaderboard!",
		"Steam manager not initialised. ",
		"World",
		"You",
		"Friends",
		"For Just Add Water (Development) Ltd:",
		"Programming:",
		"Art:",
		"Quality Assurance:",
		"Support:",
		"Thanks To:",
		"Adventure mode uses an auto-save system, do not turn off the game when you see this icon:",
		"Unable to load save game. Save game appears to be corrupted. More information may be available in the PlayerLog.txt file. ",
		"Resolution",
		"Updating…",
		"",
	""
	};
	public static string[] LOC_FrenchStrings = {
		"En association avec",
		"Commencer",
		"Jouer",
		"Paramètres",
		"Quitter le jeu",
		"Graphismes",
		"Commandes",
		"Paramètres des graphismes",
		"Préréglage :",
		"AA :",
		"Type d'AA :",
		"V-Sync :",
		"Images par seconde :",
		"Ombres :",
		"Textures :",
		"Flou lumineux :",
		"Vignette :",
		"Ordinateur portable",
		"Ordinateur de bureau",
		"Ordinateur de gamer",
		"Faible",
		"Moyen",
		"Élevé",
		"Off",
		"On",
		"Nouvelle partie",
		"Continuer",
		"Retour",
		"Suivant",
		"Sélectionnez l'orientation des commandes",
		"Tester la sélection",
		"Appuyez pour revenir :",
		"Sauvegarder et quitter",
		"Quitter",
		"Sélectionnez un mode de jeu :",
		"Aventure",
		"Old school",
		"Vies infinies. Carte. Sauvegarde du jeu. Explorez à votre rythme !",
		"Nombre fini de vies. Aucune carte. Pas de sauvegarde du jeu. Jouez contre la montre comme en 1985 !",
		"Sélectionnez un personnage :",
		"La carte n'est pas disponible en mode Old school.",
		"Par Gareth Noyce",
		"Voulez-vous vraiment supprimer cette sauvegarde ?",
		"Oui",
		"Non",
		"Sélectionnez un emplacement de sauvegarde libre",
		"Sauvegarder le jeu :",
		"Sélectionnez une partie pour continuer :",
		"Partie terminée",
		"En explorant",
		"pièces, vous :",
		"Avez trouvé",
		"canards",
		"Avez trouvé",
		"cassettes",
		"Avez sauté",
		"fois",
		"Êtes mort de",
		"façons horribles",
		"Avez parcouru",
		"kilomètres",
		"Temps total de jeu :",
		"Appuyez sur START/ÉCHAP pour retourner au menu principal",
		"Temps écoulé !",
		"Aucune vie restante !",
		"Reflets :",
		"Lumo, par :",
		"Musique :",
		"Personnages :",
		"Test :",
		"Petite amie :",
		"Apparitions :",
		"Logo Zzap!64 © Oliver Frey. Utilisé avec les permissions d'Oliver Frey et Roger Kean",
		"Multiface II utilisé avec la permission de Romantic Robot, Londres (www.romantic-robot.com)",
		"Raspberry Pi (TM) utilisé avec la permission de la fondation Raspberry Pi (www.raspberrypi.org)",
		"Llamatron utilisé avec la permission de Llamasoft Ltd (www.llamasoft.co.uk)",
		"Pimp My Spectrum utilisé avec la permission d'Ate Bit (www.atebit.org)",
		"Head Over Heels utilisé avec la permission de Jon Ritman",
		"Chimera utilisé avec la permission de Shahid Ahmad",
		"Carte Alien 8 utilisée avec la permission de Wil Overton",
		"Capture d'écran d'Amaurote utilisée avec la permission de Pickford Bros (www.zee-3.com)",
		"Capture d'écran de Rex utilisée avec la permission de Jas Austin",
		"Hold My Hand Very Tightly utilisé avec la permission de David Wilson",
		"Sprite de Jack the Nipper utilisé avec la permission d'Ian Stewart. Greg Holmes, créateur.",
		"Coups de chapeau, saluts et câlins :",
		"Et vous... ",
		"Pour Rising Star Games :",
		"Directeur général :",
		"Vice-président (RSG Inc) :",
		"Directeur de la production :",
		"Relations avec les développeurs :",
		"Relations publiques :",
		"Marketing :",
		"Marketing numérique :",
		"Prêt... ",
		"Partez !",
		"Annuler",
		"Définir les actions par défaut :",
		"Haut :",
		"Bas :",
		"Gauche :",
		"Droite :",
		"Saut :",
		"Lumière de la baguette :",
		"Carte :",
		"Livre (pause) :",
		"Incliner vers la gauche :",
		"Incliner vers la droite :",
		"Reconfigurer les commandes",
		"Cliquez sur le bouton de la commande que vous voulez modifier, puis appuyez sur le bouton désiré :",
		"Paramètres",
		"Certains paramètres ne seront effectifs qu'à partir de la pièce suivante",
		"Classement",
		"Crédits",
		"Délai d'attente du classement dépassé",
		"Aucune entrée trouvée... ",
		"Impossible de trouver un classement !",
		"Gestionnaire Steam non initialisé",
		"Monde",
		"Vous",
		"Amis",
		"Pour Just Add Water (Development) Ltd :",
		"Programmation :",
		"Graphismes :",
		"Assurance qualité :",
		"Assistance :",
		"Remerciements :",
		"Le mode Aventure utilise la sauvegarde automatique. Ne quittez pas le jeu lorsque vous voyez cette icône :",
		"Impossible de charger la sauvegarde. La sauvegarde est corrompue. Plus d'informations peuvent être disponibles dans le fichier PlayerLog.txt.",
		"Résolution",
		"Réactualisation",
		"",
	""
	};
	public static string[] LOC_GermanStrings = {
		"Zusammen mit",
		"Start",
		"Spiel starten",
		"Einstellungen",
		"Spiel verlassen",
		"Grafik",
		"Steuerung",
		"Grafikeinstellungen",
		"Voreinstellung:",
		"AA:",
		"AA-Typ:",
		"V-Synch.:",
		"Frames/s:",
		"Schatten:",
		"Texturen:",
		"Bloom:",
		"Vignette:",
		"Laptop",
		"Desktop-Rechner",
		"Gaming-PC",
		"Niedrig",
		"Mittel",
		"Hoch",
		"Aus",
		"An",
		"Neues Spiel",
		"Spiel fortsetzen",
		"Zurück",
		"Weiter",
		"Bitte Controller-Ausrichtung einstellen",
		"Auswahl testen",
		"Zum Zurückkehren drücken:",
		"Speichern und Beenden",
		"Beenden",
		"Bitte wähle einen Spieltyp aus:",
		"Adventure",
		"Old School",
		"Unendlich viele Leben. Karte. Spiel speichern. Erkunde alle in deinem Tempo!",
		"Begrenzte Anzahl Leben. Keine Karte. Keine Speicherstände. Spiel gegen die Uhr, als wäre es 1985!",
		"Bitte wähle einen Charakter:",
		"Karte ist im Old-School-Modus nicht verfügbar.",
		"Von Gareth Noyce",
		"Bist du sicher, dass dieser Spielstand gelöscht werden soll?",
		"Ja",
		"Nein",
		"Bitte wähle einen leeren Speicherstand",
		"Speicherstand:",
		"Bitte wähle zum Fortsetzen ein Spiel aus:",
		"Spiel Vorbei",
		"Beim Erkunden von",
		"Räumen ist dir Folgendes gelungen:",
		"Du hast",
		"Enten gesammelt",
		"Du hast",
		"Kassetten gefunden",
		"Du bist",
		"-mal gesprungen",
		"Du bist auf",
		"furchtbare Arten gestorben",
		"Und hast",
		"Kilometer zurückgelegt",
		"Gesamtzeit:",
		"Drücke START/ESC, um zum Hauptmenü zurückzukehren",
		"Keine Zeit mehr!",
		"Keine Leben übrig!",
		"Reflektionen:",
		"Lumo, von:",
		"Musik:",
		"Charakterdesign:",
		"Tests:",
		"Freundin:",
		"Gastauftritte:",
		"Zzap!64-Logo © Oliver Frey. Genutzt mit freundlicher Erlaubnis von Oliver Frey und Roger Kean",
		"Multiface II genutzt mit freundlicher Erlaubnis des Romantic Robot, London (www.romantic-robot.com)",
		"Raspberry Pi (TM) genutzt mit freundlicher Erlaubnis der Raspberry Pi Foundation (www.raspberrypi.org)",
		"Llamatron genutzt mit freundlicher Erlaubnis von Llamasoft Ltd (www.llamasoft.co.uk)",
		"Pimp My Spectrum genutzt mit freundlicher Erlaubnis von Ate Bit (www.atebit.org)",
		"Head Over Heels genutzt mit freundlicher Erlaubnis von Jon Ritman",
		"Chimera genutzt mit freundlicher Erlaubnis von Shahid Ahmad",
		"Alien 8 mapgenutzt mit freundlicher Erlaubnis vonWil Overton",
		"Amaurote-Screenshot genutzt mit freundlicher Erlaubnis von Pickford Bros (www.zee-3.com)",
		"Rex-Screenshot genutzt mit freundlicher Erlaubnis von Jas Austin",
		"‘Hold My Hand Very Tightly' genutzt mit freundlicher Erlaubnis von David Wilson",
		"‘Jack the Nipper' -Sprite genutzt mit freundlicher Erlaubnis von Ian Stewart. Greg Holmes, Schöpfer.",
		"Gelüpfte Hüte, Grüße und Umarmungen:",
		"Und euch... ",
		"Für Rising Star Games:",
		"Leitung:",
		"Vizevorstand (RSG Inc):",
		"Produktionsleitung:",
		"Entwicklerkommunikation:",
		"Öffentlichkeitsarbeit:",
		"Marketing:",
		"Digitales Marketing:",
		"Mach dich bereit... ",
		"Los!",
		"Abbrechen",
		"Standard einstellen",
		"Hoch:",
		"Runter:",
		"Links:",
		"Rechts:",
		"Spingen:",
		"Stablicht:",
		"Karte:",
		"Buch (Pause):",
		"Links kippen:",
		"Rechts kippen:",
		"Steuerung neu festlegen",
		"Klicke den Button der Steuerung an, die du ändern möchtest, und drücke dann die gewünschte Taste:",
		"Einstellungen",
		"Einige Einstellungen werden erst im nächsten Raum geändert",
		"Rangliste",
		"Mitwirkende",
		"Ranglisten-Anfrage abgelaufen",
		"Keine Einträge gefunden... ",
		"Rangliste konnte nicht gefunden werden!",
		"Steam-Manager nicht initialisiert.",
		"Welt",
		"Du",
		"Freunde",
		"Für Just Add Water (Development) Ltd:",
		"Programmierung:",
		"Künstlerische Leitung:",
		"Qualitätssicherung:",
		"Unterstützung:",
		"Dank an:",
		"Der Adventure-Modus beinhaltet ein Autospeicher-System. Schalte das Spiel nicht ab, wenn du dieses Symbol siehst:",
		"Speicherstand kann nicht geladen werden. Der Speicherstand scheint beschädigt zu sein. Mehr Informationen findest du in der Datei PlayerLog.txt.",
		"Auflösung",
		"Aktualisierung",
		"",
	""
	};
	public static string[] LOC_SpanishStrings = {
		"En asociación con",
		"Empezar",
		"Jugar al juego",
		"Configuración",
		"Salir del juego",
		"Gráficos",
		"Controles",
		"Ajustes de gráficos",
		"Predefinido:",
		"Aa:",
		"Tipo de aa:",
		"V-Sync:",
		"FPS:",
		"Sombras:",
		"Texturas:",
		"Efecto de halo:",
		"Efecto de viñeta:",
		"Portátil",
		"Sobremesa",
		"Equipo",
		"Bajo",
		"Medio",
		"Alto",
		"No",
		"Sí",
		"Nueva partida",
		"Continuar partida",
		"Volver",
		"Siguiente",
		"Elige la orientación del mando.",
		"Probar selección",
		"Pulsa para volver:",
		"Guardar y salir",
		"Salir",
		"Elige un tipo de partida:",
		"Aventura",
		"Clásico",
		"Vidas ilimitadas. Mapa. Partidas guardadas. ¡Explora a tu ritmo!",
		"Vidas limitadas. Sin mapa. Sin partidas guardadas. ¡Juega contrarreloj como si estuvieras en 1985!",
		"Elige un personaje:",
		"Mapa no disponible en el modo Clásico.",
		"Por Gareth Noyce",
		"¿Seguro que quieres eliminar esta partida guardada?",
		"Sí",
		"No",
		"Elige un espacio vacío para guardar la partida.",
		"Partida guardada:",
		"Elige una partida para continuar:",
		"Fin del juego",
		"Mientras explorabas",
		"salas:",
		"Recogiste",
		"patos",
		"Encontraste",
		"casetes",
		"Saltaste",
		"veces",
		"Moriste de",
		"formas horribles",
		"Y caminaste",
		"km",
		"Tiempo total:",
		"Pulsa START/ESC para volver al menú principal.",
		"¡El tiempo se acaba!",
		"¡No te quedan vidas!",
		"Reflejos:",
		"Lumo, por:",
		"Música:",
		"Diseño de personajes:",
		"Pruebas:",
		"Novia:",
		"Cameos",
		"Logotipo de Zzap!64 © Oliver Frey. Se utiliza con el permiso amablemente concedido por Oliver Frey y Roger Kean",
		"Multiface II se utiliza con el permiso amablemente concedido por Romantic Robot, Londres (www.romantic-robot.com)",
		"Raspberry Pi (TM) se utiliza con el permiso amablemente concedido por Raspberry Pi Foundation (www.raspberrypi.org)",
		"Llamatron se utiliza con el permiso amablemente concedido por Llamasoft Ltd (www.llamasoft.co.uk)",
		"Pimp My Spectrum se utiliza con el permiso amablemente concedido por Ate Bit (www.atebit.org)",
		"Head Over Heels se utiliza con el permiso amablemente concedido por Jon Ritman",
		"Chimera se utiliza con el permiso amablemente concedido por Shahid Ahmad",
		"El mapa Alien 8 se utiliza con el permiso amablemente concedido por Wil Overton",
		"La captura de pantalla de Amaurote se utiliza con el permiso amablemente concedido por los Pickford Bros (www.zee-3.com)",
		"La captura de pantalla de Rex se utiliza con el permiso amablemente concedido por Jas Austin",
		"‘Hold My Hand Very Tightly' se utiliza con el permiso amablemente concedido por David Wilson",
		"‘Jack the Nipper' se utiliza con el permiso amablemente concedido por Ian Stewart. Greg Holmes, creador.",
		"Saludos, reverencias y abrazos:",
		"Y a ti…",
		"Para Rising Star Games:",
		"Director jefe:",
		"Vicepresidente (RSG Inc):",
		"Coordinador de producción:",
		"Relaciones con el desarrollador",
		"RR. HH.:",
		"Marketing:",
		"Marketing digital:",
		"Preparado…",
		"¡Ya!",
		"Cancelar",
		"Establecer valores predeterminados",
		"Arriba:",
		"Abajo:",
		"Izquierda:",
		"Derecha:",
		"Saltar:",
		"Luz de la varita:",
		"Mapa:",
		"Libro (pausa):",
		"Inclinar hacia la izquierda:",
		"Inclinar hacia la derecha:",
		"Volver a definir controles",
		"Haz clic en el botón del control que quieras cambiar y después pulsa para introducir la opción deseada.",
		"Configuración",
		"Algunos ajustes solo tendrán efecto en la siguiente sala.",
		"Marcador",
		"Créditos",
		"Se ha agotado el tiempo de espera de la solicitud del marcador.",
		"No se encontraron entradas…",
		"¡No se puede encontrar un marcador!",
		"El administrador de Steam no se inicializó.",
		"Mundo",
		"Tú",
		"Amigos",
		"Para Just Add Water (Development) Ltd:",
		"Programación:",
		"Diseño artístico:",
		"Control de calidad:",
		"Soporte:",
		"Gracias a:",
		"El modo Aventura utiliza una función de guardado automático. No apagues el juego cuando veas este icono:",
		"No se puede cargar la partida guardada. Parece que la partida guardada está dañada. Puede que el archivo PlayerLog.txt contenga más información.",
		"Resolución ",
		"Actualizando",
		"",
	""
	};
	public static string[] LOC_ItalianStrings = {
		"In collaborazione con",
		"Inizia",
		"Gioca",
		"Impostazioni",
		"Esci dal gioco",
		"Grafica",
		"Controlli",
		"Impostazioni grafiche",
		"Predefinito:",
		"AA:",
		"Tipo di AA:",
		"V-Sync:",
		"FPS:",
		"Ombre:",
		"Texture:",
		"Bloom:",
		"Vignetta:",
		"Portatile",
		"Desktop",
		"Computer",
		"Basso",
		"Medio",
		"Alto",
		"Off",
		"On",
		"Nuova partita",
		"Continua partita",
		"Indietro",
		"Successivo",
		"Seleziona l’orientamento del controller",
		"Test impostazioni",
		"Premi per tornare:",
		"Salva & Esci",
		"Esci",
		"Seleziona un tipo di partita:",
		"Avventura",
		"Classica",
		"Vite infinite. Mappa. Salvataggi. Prenditi il tempo per esplorare!",
		"Vite limitate. Niente mappa. Nessun salvataggio. Gioca contro il tempo come nel 1985!",
		"Scegli un personaggio:",
		"La mappa non è disponibile nella modalità Classica.",
		"Di Gareth Noyce",
		"Vuoi davvero eliminare questo salvataggio?",
		"Sì",
		"No",
		"Seleziona uno slot vuoto dove salvare",
		"Salvataggio:",
		"Seleziona una partita per continuare:",
		"Fine partita",
		"Esplorando le",
		"stanze, puoi:",
		"Raccolte",
		"Anatre",
		"Trovate",
		"Cassette",
		"Saltato",
		"volte",
		"Morto in",
		"modi orrendi",
		"E camminato per",
		"chilometri",
		"Tempo totale:",
		"Premi INIZIA/ESC per tornare al menu principale",
		"Fine del tempo!",
		"Nessuna vita rimasta!",
		"Riflessioni:",
		"Lumo, di:",
		"Musica:",
		"Grafica personaggi:",
		"Test:",
		"Fidanzata:",
		"Cameo:",
		"Logo Zzap!64 © Oliver Frey. Usato per gentile concessione di Oliver Frey e Roger Kean",
		"Multiface II utilizzato per gentile concessone di Romantic Robot, London (www.romantic-robot.com)",
		"Raspberry Pi (TM) utilizzato per gentile concessione della Raspberry Pi Foundation (www.raspberrypi.org)",
		"Llamatron utilizzato per gentile concessione di Llamasoft Ltd (www.llamasoft.co.uk)",
		"Pimp My Spectrum utilizzato per gentile concessione di Ate Bit (www.atebit.org)",
		"Head Over Heels utilizzata per gentile concessione di Jon Ritman",
		"Chimera usato per gentile concessione di Shahid Ahmad",
		"Alien 8 map usata per gentile concessione di Wil Overton",
		"Amaurote screenshot used by kind permission of the Pickford Bros (www.zee-3.com)",
		"Rex Screenshot used by kind permission of Jas Austin",
		"‘Hold My Hand Very Tightly' usata per gentile concessione di David Wilson",
		"Jack the Nipper usato per gentile concessione di Ian Stewart. Greg Holmes, creatore.",
		"Giù il cappello, saluti & abbracci a:",
		"E tu...",
		"Per Rising Star Games:",
		"Direttore Generale:",
		"Vicepresidente (RSG Inc):",
		"Responsabile produzione:",
		"Relazioni con gli sviluppatori:",
		"PR:",
		"Marketing:",
		"Marketing digitale:",
		"Preparati...",
		"Vai!",
		"Annulla",
		"Imposta valori predefiniti",
		"Su:",
		"Giù:",
		"Sinistra:",
		"Destra:",
		"Salta:",
		"Luce:",
		"Mappa:",
		"Libro (Pausa):",
		"Inclinati a sinistra:",
		"Inclinati a destra:",
		"Reimposta controlli",
		"Clicca il pulsante per il controllo che vuoi cambiare, poi premi il tasto desiderato:",
		"Impostazioni",
		"Alcune impostazioni avranno effetto solo nella prossima stanza",
		"Classifica",
		"Riconoscimenti",
		"Richiesta della classifica scaduta",
		"Nessun risultato trovato...",
		"Impossibile trovare una classifica!",
		"Steam manager non inizializzato.",
		"Mondo",
		"Tu",
		"Amici",
		"Per Just Add Water (Development) Ltd:",
		"Programmazione:",
		"Grafica:",
		"Controllo di qualità:",
		"Supporto:",
		"Grazie a:",
		"La modalità avventura fa uso di un sistema di salvataggio automatico, non chiudere il gioco quando vedi questa icona:",
		"Impossibile caricare il salvataggio. Il salvataggio sembra essere danneggiato. Potresti trovare qualche informazione aggiuntiva nel file PlayerLog.txt.",
		"Risoluzione",
		"In aggiornamento",
		"",
	""
	};
	public static string[] LOC_RussianStrings = {
		"Совместно с",
		"Начать",
		"Играть",
		"Настройки",
		"Выйти из игры",
		"Графика",
		"Управление",
		"Настройки графики",
		"Предустановка:",
		"Сглаживание:",
		"Тип сглаживания:",
		"Кадровая синхронизация:",
		"Частота кадров:",
		"Тени:",
		"Текстуры:",
		"Ореол:",
		"Заставка:",
		"Ноутбук",
		"ПК",
		"Оснастка",
		"Низкое",
		"Среднее",
		"Высокое",
		"Выкл.",
		"Вкл.",
		"Новая игра",
		"Продолжить игру",
		"Назад",
		"Далее",
		"Выберите ориентацию контроллера",
		"Проверить выбор",
		"Нажмите, чтобы вернуться:",
		"Сохранить и выйти",
		"Выйти",
		"Выберите тип игры:",
		"Приключение",
		"Старая школа",
		"Бесконечное число жизней. Карта. Сохранение. Путешествие в собственном времени!",
		"Конечное число жизней. Нет карты. Нет сохранения. Игра на время, как в 1985 году!",
		"Выберите персонажа:",
		"В режиме Старой школы карты нет.",
		"По Gareth Noyce",
		"Действительно удалить эту сохраненную игру?",
		"Да",
		"Нет",
		"Выберите пустой слот для сохранения игры",
		"Сохранить игру:",
		"Выберите игру для продолжения:",
		"Игра окончена",
		"Исследуя",
		"комнат, вы:",
		"собрали",
		"уток",
		"нашли",
		"кассет",
		"подпрыгнули",
		"раз",
		"умерли",
		"ужасными способами",
		"и прошли",
		"километров",
		"Общее время:",
		"Нажмите ПУСК/ESC для возврата в главное меню",
		"Время закончилось!",
		"Жизней не осталось!",
		"Отражения:",
		"Lumo:",
		"Музыка:",
		"Персонажи:",
		"Тестирование:",
		"Подружка:",
		"Эпизоды:",
		"Zzap!64 logo © Oliver Frey. Используется с разрешения Oliver Frey и Roger Kean",
		"Multiface II используется с разрешения Romantic Robot, London (www.romantic-robot.com)",
		"Raspberry Pi (TM) используется с разрешения Raspberry Pi Foundation (www.raspberrypi.org)",
		"Llamatron используется с разрешения Llamasoft Ltd (www.llamasoft.co.uk)",
		"Pimp My Spectrum используется с разрешения Ate Bit (www.atebit.org)",
		"Head Over Heels используется с разрешения Jon Ritman",
		"Chimera используется с разрешения Shahid Ahmad",
		"Alien 8 map используется с разрешения Wil Overton",
		"Amaurote screenshot используется с разрешения the Pickford Bros (www.zee-3.com)",
		"Rex Screenshot используется с разрешения Jas Austin",
		"‘Hold My Hand Very Tightly' используется с разрешения David Wilson",
		"‘Jack the Nipper' sprite используется с разрешения Ian Stewart. Greg Holmes, creator.",
		"Благодарности, приветы и объятия:",
		"И вам... ",
		"От Rising Star Games:",
		"Управляющий директор:",
		"Вице-президент (RSG Inc):",
		"Выпускающий директор:",
		"Отношения с разработчиками:",
		"PR:",
		"Маркетинг:",
		"Цифровой маркетинг:",
		"Приготовьтесь... ",
		"Вперед!",
		"Отмена",
		"К настройкам по умолчанию",
		"Вверх:",
		"Вниз:",
		"Влево:",
		"Вправо:",
		"Прыгнуть:",
		"Свет палочки:",
		"Карта:",
		"Книга (пауза):",
		"Наклон влево:",
		"Наклон вправо:",
		"Изменить управление",
		"Нажмите кнопку управления, которую хотите изменить, затем нажмите ту, которую хотите назначить:",
		"Настройки",
		"Некоторые настройки вступят в силу только в следующей комнате",
		"Лидеры",
		"Авторы",
		"Закончилось время ожидания таблицы лидеров",
		"Данные не найдены... ",
		"Невозможно найти таблицу лидеров!",
		"Менеджер Steam не включен.",
		"Мир",
		"Вы",
		"Друзья",
		"For Just Add Water (Development) Ltd:",
		"Программирование:",
		"Графика:",
		"Контроль качества:",
		"Поддержка:",
		"Благодарим:",
		"В режиме приключения используется система автосохранения. Не отключайте игру, если видите такой значок:",
		"Невозможно загрузить игру. Похоже, функция сохранения игры поломана. Подробности можно найти в файле PlayerLog.txt.",
		"Resolução",
		"Atualização",
		"",
	""
	};
	public static string[] LOC_BrazilianStrings = {
		"Em parceria com",
		"Iniciar",
		"Jogar",
		"Configurações",
		"Sair do jogo",
		"Gráficos",
		"Controles",
		"Configurações gráficas",
		"Predefinição:",
		"AA:",
		"Tipo de AA:",
		"V-Sync:",
		"FPS:",
		"Sombras:",
		"Texturas:",
		"Bloom:",
		"Vinheta:",
		"Laptop",
		"Desktop",
		"Computador",
		"Baixo",
		"Médio",
		"Alto",
		"Não",
		"Sim",
		"Novo jogo",
		"Continuar",
		"Voltar",
		"Avançar",
		"Escolha o tipo de controle",
		"Testar controle",
		"Aperte para voltar",
		"Salvar e sair",
		"Sair",
		"Escolha um tipo de jogo",
		"Aventura",
		"Retrô",
		"Vidas infinitas. Com mapa. Com salvamento. Explore sem pressa!",
		"Vidas finitas. Sem mapa. Sem salvamento. Jogue contra o tempo como se fosse 1985!",
		"Escolha um personagem:",
		"Mapa não disponível no modo Retrô.",
		"Por Gareth Noyce",
		"Quer mesmo excluir esse jogo salvo?",
		"Sim",
		"Não",
		"Escolha um espaço vazio para salvar o jogo",
		"Salvar o jogo:",
		"Escolha um jogo para continuar:",
		"Fim do jogo",
		"Enquanto explorava",
		"salas, você:",
		"Pegou",
		"patos",
		"Encontrou",
		"fitas cassetes",
		"Pulou",
		"vezes",
		"Morreu de",
		"formas horríveis",
		"E caminhou",
		"quilômetros",
		"Tempo total:",
		"Aperte START/ESC para retornar ao menu principal",
		"Acabou o tempo!",
		"Acabaram as vidas!",
		"Reflexos:",
		"Lumo, por:",
		"Música:",
		"Arte dos personagens:",
		"Testes:",
		"Namorada:",
		"Participações:",
		"Zzap!64 logo © Oliver Frey. Usado sob permissão de Oliver Frey e Roger Kean",
		"Multiface II usado sob permissão de Romantic Robot, London ()",
		"Raspberry Pi (TM) usado sob permissão da Raspberry Pi Foundation ()",
		"Llamatron usado sob permissão de Llamasoft Ltd ()",
		"Pimp My Spectrum usado sob permissão de Ate Bit ()",
		"Head Over Heels usado sob permissão de Jon Ritman",
		"Chimera usado sob permissão de Shahid Ahmad",
		"Alien 8 map usado sob permissão de Wil Overton",
		"Amaurote screenshot usado sob permissão de Pickford Bros (www.zee-3.com)",
		"Rex Screenshot usado sob permissão de Jas Austin",
		"‘Hold My Hand Very Tightly' usado sob permissão de David Wilson",
		"‘Jack the Nipper' sprite usado sob permissão de Ian Stewart. Greg Holmes, criador.",
		"Cumprimentos, saudações e abraços:",
		"E a você...",
		"Para a Rising Star Games:",
		"Diretor-executivo:",
		"Vice-presidente (RSG Inc):",
		"Gerente de Produção:",
		"Relações com Desenvolvedores:",
		"RP:",
		"Marketing:",
		"Marketing digital:",
		"Prepare-se...",
		"Vai!",
		"Cancelar",
		"Definir padrões",
		"Cima:",
		"Baixo:",
		"Esquerda:",
		"Direita:",
		"Pular:",
		"Luz da varinha:",
		"Mapa:",
		"Livro (Pausa):",
		"Inclinar para a esquerda:",
		"Inclinar para a direita:",
		"Redefinir controles",
		"Clique no botão que quer trocar e aperte a tecla desejada:",
		"Configurações",
		"Algumas configurações só terão efeito na próxima sala",
		"Placar de líderes",
		"Créditos",
		"Sem resposta para o pedido do placar de líderes",
		"Nenhuma entrada encontrada...",
		"Não foi possível encontrar um placar de líderes!",
		"O gerenciador do Steam não foi iniciado.",
		"Global",
		"Você",
		"Amigos",
		"Para a Just Add Water (Development) Ltd:",
		"Programação:",
		"Arte:",
		"Controle de Qualidade:",
		"Suporte:",
		"Agradecimentos:",
		"O modo Aventura usa um sistema de autossalvamento, não desligue o jogo enquanto este ícone estiver aparecendo:",
		"Não foi possível carregar o jogo salvo. O arquivo parece estar danificado. Encontre mais informações no arquivo PlayerLog.txt.",
		"Разрешение",
		"обновление",
		"",
	""
	};
	public static string[] LOC_JapaneseStrings = {
		"制作協力:",
		"スタート",
		"プレイ",
		"設定",
		"終了",
		"グラフィック",
		"コントロール",
		"グラフィック設定",
		"プリセット:",
		"AA:",
		"AA:タイプ:",
		"V-Sync:",
		"FPS:",
		"影:",
		"テクスチャ:",
		"ブルーム:",
		"ぼかし:",
		"ノートパソコン",
		"デスクトップ",
		"リグ",
		"低",
		"中",
		"高",
		"オフ",
		"オン",
		"ニューゲーム",
		"コンティニュー",
		"戻る",
		"進む",
		"移動方向を選択してください",
		"テスト",
		"戻る:",
		"セーブして終了",
		"終了",
		"ゲームモードを選択してください:",
		"アドベンチャー",
		"クラシック",
		"ライフ無制限、マップあり、セーブ可能。あなた自身のペースで旅をしましょう！",
		"ライフ制限あり、マップなし、セーブ不可。1985年のドクとマーティのように、これは時間との勝負です！",
		"キャラクターを選択してください:",
		"クラシックモードではマップは表示されません。",
		"作　ガレス・ノイス",
		"このセーブデータを本当に削除しますか？",
		"はい",
		"いいえ",
		"空のセーブスロットを選択してください",
		"セーブ:",
		"セーブデータを選んでください:",
		"ゲームオーバー",
		"",
		"部屋を探索中に、あなたは:",
		"アヒルを",
		"匹拾った",
		"カセットを",
		"本見つけた",
		"",
		"回ジャンプした",
		"",
		"回おぞましく死んだ",
		"",
		"km歩いた",
		"合計時間:",
		"START/ESCを押すとメインメニューに戻ります",
		"時間切れ！",
		"ライフ切れ！",
		"反射:",
		"Lumo制作メンバー:",
		"ミュージック:",
		"キャラクターアート:",
		"テスト:",
		"ガールフレンド:",
		"カメオ:",
		"Zzap!64 logo © Oliver Frey。 Oliver FreyおよびRoger Keanの許可により使用。",
		"Multiface IIはRomantic Robot, London (www.romantic-robot.com)の許可により使用。",
		"Raspberry Pi ™はRaspberry Pi Foundation (www.raspberrypi.org)の許可により使用。",
		"Llamatronは Llamasoft Ltd (www.llamasoft.co.uk)の許可により使用。",
		"Pimp My SpectrumはAte Bit (www.atebit.org)の許可により使用。",
		"Head Over HeelsはJon Ritmanの許可により使用。",
		"ChimeraはShahid Ahmadの許可により使用。",
		"Alien 8 mapはWil Overtonの許可により使用。",
		"Amaurote screenshotはPickford Bros (www.zee-3.com)の許可により使用。",
		"Rex ScreenshotはJas Austinの許可により使用。",
		"Hold My Hand Very Tightly'はDavid Wilsonの許可により使用。",
		"Jack the Nipper'はIan Stewart. Greg Holmes, creatorの許可により使用。",
		"深謝、敬礼、ハグ:",
		"そして、あなた…",
		"Rising Star Gamesより:",
		"マネージングディレクター:",
		"副社長（RSG Inc）:",
		"プロダクションマネージャー:",
		"デベロッパー・リレーションズ:",
		"PR:",
		"マーケティング:",
		"デジタルマーケティング:",
		"よーい...",
		"どん!",
		"キャンセル",
		"ディフォルトに設定",
		"上:",
		"下:",
		"左:",
		"右:",
		"ジャンプ:",
		"ライトワンド:",
		"マップ:",
		"ブック（一時停止）:",
		"左に傾く:",
		"右に傾く:",
		"コントロールの再設定",
		"コントロールを変更したいキーをクリックし、その後、変更先のキーをクリックしてください:",
		"設定",
		"一部の設定は隣の部屋への移動後、有効になります",
		"ランキング",
		"クレジット",
		"ランキングのリクエストがタイムアウトになりました",
		"エントリーが見つかりません...",
		"ランキングを見つけることができませんでした！",
		"Steamマネージャーが初期化されていません。",
		"ワールド",
		"あなた",
		"フレンド",
		"Just Add Water (Development) Ltdより:",
		"プログラミング:",
		"アート:",
		"品質保証:",
		"サポート:",
		"Thanks To:",
		"アドベンチャーモードではオートセーブが行われます。このアイコンが表示されている間、ゲームを終了しないでください。",
		"セーブデータを読み込めませんでした。セーブデータが破損しているようです。詳細に関してはPlayerLog.txtに記述されている場合があります。",
		"",
		"",
		"",
	""
	};
	public static string[] LOC_FinnishStrings = {
		"yhteistyössä:",
		"Aloita",
		"Pelaa",
		"Asetukset",
		"Poistu",
		"Grafiikka",
		"Ohjainkomennot",
		"Grafiikka-asetukset",
		"Esiasetus:",
		"AA:",
		"AA-taso:",
		"V-sync:",
		"FPS:",
		"Varjot:",
		"Tekstuurit:",
		"Bloom:",
		"Vinjetti:",
		"Kannettava:",
		"Pöytäkone:",
		"Korkein:",
		"Matala",
		"Keskitaso",
		"Korkea",
		"Pois",
		"Päällä",
		"Uusi peli",
		"Jatka peliä",
		"Takaisin",
		"Seuraava",
		"Valitse ohjaimen suuntaus",
		"Kokeile valintaa",
		"Takaisin:",
		"Tallenna ja lopeta",
		"Lopeta",
		"Valitse pelityyppi:",
		"Seikkailu",
		"Old School",
		"Loputtomat elämät. Kartta. Tallentaminen. Tutki pelimaailmaa ajan kanssa!",
		"Rajalliset elämät. Ei karttaa. Ei tallentamista. Taistele aikaa vastaan, ihan kuin vuonna 1985!",
		"Valitse hahmo:",
		"Kartta ei ole käytössä Old School -moodissa",
		"(C) Gareth Noyce",
		"Haluatko varmasti poistaa tämän tallennuksen?",
		"Kyllä",
		"Ei",
		"Valitse tyhjä tallennuspaikka",
		"Tallennus:",
		"Valitse jatkettava peli:",
		"Peli Ohi",
		"Tutkit",
		"huonetta",
		"Keräsit",
		"ankkaa",
		"Löysit",
		"kasettia",
		"Hyppäsit",
		"hyppyä",
		"Kuolit",
		"tuskallista kertaa",
		"ja matkasit",
		"kilometriä",
		"Kokonaisaika",
		"Paina START/ESC palataksesi päävalikkoon",
		"Aika loppu!",
		"Elämät loppuivat!",
		"Heijastukset:",
		"Lumon luoja:",
		"Musiikki:",
		"Hahmotaide:",
		"Testaus:",
		"Tyttöystävä:",
		"Vierailijat:",
		"Zzap!64 logo © Oliver Frey. Käytössä Oliver Freyn and Roger Keanin suostumuksella",
		"Multiface II käytössä Romantic Robotin (Lontoo, www.romantic-robot.com) suostumuksella",
		"Raspberry Pi (TM) käytössä Raspberry Pi Foundationin (www.raspberrypi.org) suostumuksella",
		"Llamatron käytössä Llamasoft Limitedin suostumuksella (www.llamasoft.co.uk)",
		"Pimp My Spectrum käytössä Ate Bitin suostumuksella (www.atebit.org)",
		"Head Over Heels käytössä Jon Ritmanin suostumuksella",
		"Chimera käytössä Shahid Ahmadin suostumuksella",
		"Alien 8 -kartta käytössä Wil Overtonin suostumuksella",
		"Amaurote-kuvankaappaus käytössä Pickford Brosin suostumuksella (www.zee-3.com)",
		"Rex-kuvankaappaus käytössä Jas Austinin suostumuksella",
		"'Hold My Hand Very Tightly' käytössä David Wilsonin suostumuksella",
		"'Jack the Nipper' -spritekuva käytössä Ian Stewartin suostumuksella. Alkuperäinen luoja: Greg Holmes.",
		"Hatunnostot, kiitokset ja halaukset:",
		"Ja tietenkin sinä...",
		"Rising Star Games:",
		"Managing Director:",
		"Vice President (RSG Inc):",
		"Production Manager:",
		"Developer Relations:",
		"PR:",
		"Marketing:",
		"Digital Marketing:",
		"Valmiina...",
		"Aloita!",
		"Peruuta",
		"Aseta oletukset",
		"Ylös:",
		"Alas:",
		"Vasen:",
		"Oikea:",
		"Hyppy:",
		"Sauvan valo:",
		"Kartta:",
		"Kirja (tauko):",
		"Kallistus vasempaan:",
		"Kallistus oikeaan:",
		"Määritä uudelleen",
		"Napsauta ohjainkomentoa ja paina sen jälkeen näppäintä jota haluat siihen käyttää.",
		"Asetukset",
		"Jotkut asetukset tulevat voimaan vasta, kun olet siirtynyt seuraavaan huoneeseen.",
		"Tuloslista",
		"Tekijät",
		"Tuloslistaan yhdistäminen aikakatkaistiin",
		"Ei merkintöjä...",
		"Tuloslistoja ei löydy!",
		"Steam-manageria ei ole alustettu.",
		"Kaikki",
		"Sinä",
		"Ystävät",
		"Just Add Water (Development) Ltd:",
		"Programming:",
		"Art:",
		"Quality Assurance:",
		"Support:",
		"Thanks To:",
		"Seikkailumoodissa on käytössä automaattinen tallennus. Älä sulje peliä jos näet tämän ikonin:",
		"Tallennuksen lataaminen ei onnistu. Tallennus saattaa olla viallinen. Lisätietoja löytyy PlayerLog.txt-tiedostosta.",
		"Resoluutio",
		"",
		"",
	""
	};
}